name = "biocompute"
description = "A Bootstrap-based theme for Hugo."
homepage = "https://github.com/biocompute-objects/BCO_Specification/"
tags = ["bootstrap", "responsive"]
min_version = 0.17

[author]
  name = "Nan Xiao"
  homepage = "https://nanx.me"
  repo = "https://github.com/nanxstats/bco-public-website"
